trigger:
  branches:
    include: [develop, main]

pool:
  vmImage: 'ubuntu-latest'

variables:
  # 1. Atualizamos o repositório para apontar para o seu NOVO ACR gerado pelo Bicep
  imageRepo: 'acrkk64y4rci6sqi.azurecr.io/profarma/api-trilha'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Stage de Build e Push'
  jobs:
  - job: BuildAndPush
    displayName: 'Build Docker Image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-sandbox-svc' # Service Connection da Profarma
        repository: $(imageRepo)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest

- stage: Dev
  displayName: 'Deploy para DEV'
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    displayName: 'Job Deploy DEV'
    environment: 'aks-sandbox' # Rodará automaticamente em DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Executando deploy automático no cluster de Desenvolvimento (DEV)..."
              echo "Deploy da imagem: $(imageRepo):$(tag)"
            displayName: 'Executar Deploy DEV'

- stage: Hml
  displayName: 'Deploy para HML'
  dependsOn: Dev
  jobs:
  - deployment: DeployHml
    displayName: 'Job Deploy HML'
    environment: 'aks-sandbox' # Rodará automaticamente em HML após DEV terminar
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Executando deploy automático no cluster de Homologação (HML)..."
            displayName: 'Executar Deploy HML'

- stage: Prd
  displayName: 'Deploy para PRD'
  dependsOn: Hml
  jobs:
  - deployment: DeployPrd
    displayName: 'Job Deploy PRD com Approval'
    # É aqui que conectamos o ambiente com a aprovação manual que você criou!
    environment: 'prd' 
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploy em PRODUÇÃO realizado com sucesso após aprovação manual de Flávio!"
              echo "==> EVIDENCIA (1): Pipeline multi-stage concluída <=="
            displayName: 'Executar Deploy PRD'