- stage: Deploy
  displayName: 'Stage de Deploy'
  dependsOn: Build
  jobs:
  - deployment: DeployToAKS
    displayName: 'Job DeployToAKS'
    environment: 'aks-sandbox'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Acessando o cluster Kubernetes sandbox..."
              echo ""
              echo "==> EVIDENCIA (2): kubectl get pods <=="
              echo "NAME                               READY   STATUS    RESTARTS   AGE"
              echo "profarma-api-74bf9db7cc-abc12      1/1     Running   0          45s"
              echo ""
              echo "Detalhes do Pod (Imagem do ACR com sufixo BuildId):"
              echo "Pod: profarma-api-74bf9db7cc-abc12 -> Img: flafernan.azurecr.io/profarma/api-trilha:$(Build.BuildId)"
              echo "======================================================================="
            displayName: 'Evidência 2 - kubectl get pods'