apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-profarma-trilha
  namespace: default
  annotations:
    # Vincula esta ServiceAccount à identidade da Azure via Workload Identity
    azure.workload.identity/client-id: "91e96c76-09e3-4242-8e9c-a9667dbc44a3"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "91e96c76-09e3-4242-8e9c-a9667dbc44a3" # Identidade que vai ler o Key Vault
    keyvaultName: "kv-profarma-flaviov1"     # Nome do seu Key Vault
    cloudName: "" 
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
          objectVersion: ""
    tenantId: "868933d8-38d8-4150-aec6-ec766c27f603"