apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-erro-runtime
  labels:
    app: erro-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erro-runtime
  template:
    metadata:
      labels:
        app: erro-runtime
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80