apiVersion: v1
kind: Secret
metadata:
  name: profarma-api-secret
type: Opaque
data:
  # Cole o código em base64 gerado pelo seu PowerShell na linha abaixo
  DefaultConnection: SG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlO0RhdGFiYXNlPXByb2Zhcm1hZGI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9UHJvZmFybWFTZW5oYVRyaWxoYTEyMw==
